// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoscowWiFi.WebService.ApplicationServices.Ports.Gateways.Database;

namespace MoscowWiFi.WebService.Migrations
{
    [DbContext(typeof(MoscowWiFiContext))]
    partial class MoscowWiFiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("MoscowWiFi.WebService.DomainObjects.AccessPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessFlag")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdmArea")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoverageArea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionFlag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfAccessPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("WiFiName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccessPoints");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessFlag = "asda",
                            AdmArea = "asdasd",
                            CoverageArea = 400,
                            District = "123",
                            FunctionFlag = "asdasd",
                            Location = "123",
                            Name = "123",
                            NumberOfAccessPoints = 2,
                            Password = "123",
                            WiFiName = "asda"
                        },
                        new
                        {
                            Id = 2L,
                            AccessFlag = "asda",
                            AdmArea = "asdasd",
                            CoverageArea = 400,
                            District = "123",
                            FunctionFlag = "asdasd",
                            Location = "123",
                            Name = "123",
                            NumberOfAccessPoints = 3,
                            Password = "123",
                            WiFiName = "asda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
